name: Build and deploy chrome extension

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'    

jobs:
  build:
    name: Build chrome extension
    runs-on: ubuntu-latest    
    
    steps:      
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./dist

  deploy:
    name: Deploy chrome extension
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./dist
    
    - name: Zip contents
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r extension.zip dist

    - name: Publish to Chrome store
      uses: Klemensas/chrome-extension-upload-action@v1.3
      with:
        refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
        client-id: ${{ secrets.CHROME_CLIENT_ID }}
        file-name: './extension.zip'
        app-id: ${{ secrets.CHROME_APP_ID }}
        publish: true
